const base = "http://localhost:80/api";
const login = async (e,p)=>{const r=await fetch(base+"/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:e,password:p})});return (await r.json()).token;};
const admin = await login("desarrollador@diagnosticar.ar","diagnosticar");
const HA={Authorization:"Bearer "+admin,"Content-Type":"application/json"};
const m1 = await login("medico@diagnosticar.ar","medico123");
const HM={Authorization:"Bearer "+m1,"Content-Type":"application/json"};
const pacs = await (await fetch(base+"/pacientes?limit=1",{headers:HA})).json();
const rr = await fetch(base+"/consultorio/prescriptions",{method:"POST",headers:HM,body:JSON.stringify({patientId:pacs.data[0].id,medication:"Ibuprofeno 400 mg",dosage:"1 comprimido",frequency:"cada 8 horas",duration:"5 días"})});
const rj = await rr.json();
console.log("receta:", rr.status, rj.id);
const g = await fetch(base+"/consultorio/pdf/generate",{method:"POST",headers:HM,body:JSON.stringify({sourceType:"receta",sourceId:rj.id})});
const gj = await g.json();
const p = await fetch(base+`/consultorio/pdf/${gj.id}`,{headers:HM});
(await import("node:fs")).writeFileSync("/tmp/receta.pdf", Buffer.from(await p.arrayBuffer()));
const f = new Date(rj.createdAt);
const ymd = `${f.getUTCFullYear()}${String(f.getUTCMonth()+1).padStart(2,"0")}${String(f.getUTCDate()).padStart(2,"0")}`;
const v = await fetch(`${base}/consultorio/recetas/verificar/RM-${ymd}-${String(rj.id).padStart(8,"0")}`);
console.log("verificar:", v.status, JSON.stringify(await v.json()));
const pg = await fetch("http://localhost:80/verificar-receta/abc");
console.log("pagina publica:", pg.status);
