// Frases graciosas que Manuel tira cada tanto para alegrar la jornada.
// Catálogo provisto por el usuario (jul 2026).
export const FRASES_MANUEL: string[] = [
  "Un amigo verdadero no te juzga; guarda la información para cargarte después.",
  "La amistad se fortalece compartiendo alegrías y dividiendo la cuenta.",
  "Los amigos conocen nuestros defectos, pero ya invirtieron demasiado para retirarse.",
  "La confianza consiste en prestar algo sabiendo que quizá nunca vuelva.",
  "Un buen amigo llega cuando todos se fueron y pregunta si quedó comida.",
  "La amistad no necesita explicaciones, aunque suele generar muchas anécdotas.",
  "Los amigos de toda la vida recuerdan versiones nuestras que preferiríamos eliminar.",
  "La distancia separa cuerpos; el grupo de WhatsApp destruye esa ventaja.",
  "El verdadero amigo te dice la verdad y después te acompaña a ignorarla.",
  "Algunas amistades nacen de una afinidad; otras, de odiar a la misma persona.",
  "El amor empieza con miradas y evoluciona hacia preguntas sobre qué vamos a comer.",
  "Convivir es descubrir que el amor también tiene cajones mal cerrados.",
  "Las parejas felices no discuten menos; administran mejor los silencios.",
  "El romanticismo dura hasta que alguien pregunta quién paga.",
  "En toda pareja hay dos versiones de cada historia y una suegra con documentación.",
  "El amor es aceptar al otro como es y luego iniciar discretamente las reformas.",
  "La convivencia convierte pequeños hábitos en asuntos de política exterior.",
  "Pedir perdón no siempre significa reconocer el error; a veces significa querer dormir.",
  "El matrimonio enseña a resolver juntos problemas que antes no existían.",
  "Una pareja sólida comparte sueños, responsabilidades y la contraseña del wifi.",
  "El político escucha al pueblo, sobre todo cuando se acercan las elecciones.",
  "Las promesas de campaña tienen una garantía que vence al cerrar las urnas.",
  "Todo funcionario quiere dejar una marca; pocos preguntan cuánto cuesta borrarla.",
  "En política, cambiar de opinión se llama evolución si uno conserva el cargo.",
  "La burocracia es el arte de impedir con formularios lo que nadie prohibió.",
  "Algunos dirigentes trabajan por el futuro; generalmente, por el propio.",
  "La transparencia política suele aumentar cuando la observa la oposición.",
  "El discurso público transforma los problemas concretos en soluciones gramaticales.",
  "Gobernar es establecer prioridades; hacer campaña es prometer que ninguna será necesaria.",
  "Cuando nadie entiende una medida, siempre aparece alguien diciendo que es estratégica.",
  "La experiencia llega después del error y pretende cobrar como consultora.",
  "El sentido común es gratuito, pero tiene muy poca distribución.",
  "La vida adulta consiste en esperar el viernes y preocuparse porque pasa rápido.",
  "El optimismo ayuda mucho, especialmente cuando no hay información disponible.",
  "Los problemas pequeños crecen cuando reciben atención gerencial.",
  "La paciencia es una virtud hasta que aparece una fila sin explicación.",
  "El dinero no compra felicidad, pero financia varias de sus sucursales.",
  "La tecnología ahorra tiempo que después usamos para mirar la tecnología.",
  "Envejecer es recordar perfectamente una canción y olvidar por qué entramos al cuarto.",
  "La dieta comienza siempre en una fecha que no comprometa el presente.",
  "El café no cambia la realidad, pero mejora nuestra capacidad para enfrentarla.",
  "La nostalgia es recordar el pasado sin incluir las cuotas.",
  "Madurar es entender que quedarse en casa también puede ser un gran programa.",
  "El lunes llega con la autoridad de quien nunca fue invitado.",
  "La vida sería más sencilla si viniera con subtítulos y botón para deshacer.",
];

export function fraseAleatoria(excluir?: string): string {
  const opciones = FRASES_MANUEL.filter((f) => f !== excluir);
  return opciones[Math.floor(Math.random() * opciones.length)] ?? FRASES_MANUEL[0];
}
