import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import sedesRouter from "./sedes";
import especialidadesRouter from "./especialidades";
import profesionalesRouter from "./profesionales";
import obrasSocialesRouter from "./obras_sociales";
import equivalenciasRouter from "./equivalencias";
import cajaRouter from "./caja";
import consultoriosRouter from "./consultorios";
import salasLlamadoRouter from "./salas_llamado";
import turnerasRouter from "./turneras";
import turnosRouter from "./turnos";
import pacientesRouter from "./pacientes";
import historiaClinicaRouter from "./historia_clinica";
import dashboardRouter from "./dashboard";
import importacionRouter from "./importacion";
import openaiRouter from "./openai";
import informesRouter from "./informes";
import importacionV2Router from "./importacion_v2";
import agentesRouter from "./agentes";
import hceRouter from "./hce";
import consultorioRouter from "./consultorio";
import consultorioDocsRouter from "./consultorio_docs";
import salaEsperaRouter from "./sala_espera";
import recepcionRouter from "./recepcion";
import derivacionRouter from "./derivacion";
import estadisticasRouter from "./estadisticas";
import integracionesPhiritRouter from "./integraciones_phirit";
import integracionesPulsoRouter from "./integraciones_pulso";
import klinicosRouter from "./klinicos";
import storageRouter from "./storage";
import pacsRouter from "./pacs";
import pulsoRouter from "./pulso";
import portalRouter from "./portal";
import apiPublicaRouter from "./api_publica";
import valoracionesAdminRouter from "./valoraciones_admin";
import backupsDbRouter from "./backups_db";
import robotPadronRouter from "./robot_padron";
import robotTurnosEventosRouter from "./robot_turnos_eventos";
import pacsWorkspaceRouter from "./pacs_workspace";
import pacsWorklistRouter from "./pacs_worklist";
import videollamadasRouter from "./videollamadas";
import mensajesMedicoRouter from "./mensajes-medico";
import chatRouter from "./chat";
import feedbackRouter from "./feedback";
import pacsSalaEsperaRouter from "./pacs_sala_espera";
import pacsSimRouter from "./pacs_sim";
import practicasCatalogoRouter from "./practicas_catalogo";
import ordenesPracticasRouter from "./ordenes_practicas";
import importacionAdminRouter from "./importacion_admin";
import usuariosRouter from "./usuarios";
import perfilPreferenciasRouter from "./perfil_preferencias";
import caligrafiaRouter from "./caligrafia";
import busquedaRapidaRouter from "./busqueda_rapida";
import estudiosPreviosRouter from "./estudios_previos";
import integracionEstudiosPreviosRouter from "./integracion_estudios_previos";
import integracionAutologinRouter from "./integracion_autologin";
import integracionVideollamadasRouter from "./integracion_videollamadas";
import integracionPixelLoginRouter from "./integracion_pixel_login";
import guardiaVirtualRouter from "./guardia_virtual";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(sedesRouter);
router.use(especialidadesRouter);
router.use(profesionalesRouter);
router.use(obrasSocialesRouter);
router.use(equivalenciasRouter);
router.use(cajaRouter);
router.use(consultoriosRouter);
router.use(salasLlamadoRouter);
router.use(turnerasRouter);
router.use(informesRouter);
router.use(turnosRouter);
router.use(estudiosPreviosRouter);
router.use(integracionEstudiosPreviosRouter);
router.use(integracionAutologinRouter);
router.use(integracionVideollamadasRouter);
router.use(integracionPixelLoginRouter);
router.use(pacientesRouter);
router.use(historiaClinicaRouter);
router.use(dashboardRouter);
router.use(importacionRouter);
router.use(importacionV2Router);
router.use(openaiRouter);
router.use(agentesRouter);
router.use(hceRouter);
router.use(consultorioRouter);
router.use(consultorioDocsRouter);
router.use(salaEsperaRouter);
router.use(recepcionRouter);
router.use(derivacionRouter);
router.use(estadisticasRouter);
router.use(integracionesPhiritRouter);
router.use(integracionesPulsoRouter);
router.use(klinicosRouter);
router.use(storageRouter);
router.use(pacsRouter);
router.use(pulsoRouter);
router.use(portalRouter);
router.use(apiPublicaRouter);
router.use(valoracionesAdminRouter);
router.use(robotPadronRouter);
router.use(robotTurnosEventosRouter);
router.use(pacsWorkspaceRouter);
router.use(pacsWorklistRouter);
router.use(videollamadasRouter);
router.use(mensajesMedicoRouter);
router.use(chatRouter);
router.use(feedbackRouter);
router.use(pacsSalaEsperaRouter);
// Simulador de PACS: SOLO en desarrollo (nunca se monta en producción)
if (process.env.NODE_ENV !== "production") {
  router.use(pacsSimRouter);
}
router.use(practicasCatalogoRouter);
router.use(ordenesPracticasRouter);
router.use(importacionAdminRouter);
router.use(usuariosRouter);
router.use(perfilPreferenciasRouter);
router.use(caligrafiaRouter);
router.use(busquedaRapidaRouter);
router.use(backupsDbRouter);
router.use(guardiaVirtualRouter);

export default router;
