// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/consola-recepcion/ConsolaCompleta.tsx": () => import("../components/mockups/consola-recepcion/ConsolaCompleta.tsx"),
  "./components/mockups/consola-recepcion/ErrorTecnico.tsx": () => import("../components/mockups/consola-recepcion/ErrorTecnico.tsx"),
  "./components/mockups/consola-recepcion/PrestacionManual.tsx": () => import("../components/mockups/consola-recepcion/PrestacionManual.tsx"),
  "./components/mockups/consola-recepcion/RevisionManual.tsx": () => import("../components/mockups/consola-recepcion/RevisionManual.tsx"),
  "./components/mockups/consola-recepcion/TokenAceptado.tsx": () => import("../components/mockups/consola-recepcion/TokenAceptado.tsx"),
  "./components/mockups/consola-recepcion/TokenPendiente.tsx": () => import("../components/mockups/consola-recepcion/TokenPendiente.tsx"),
  "./components/mockups/consola-recepcion/VersionTablet.tsx": () => import("../components/mockups/consola-recepcion/VersionTablet.tsx")
};
